version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:

      # Upgrade AWS CLI to the latest version
      - pip3 install --upgrade awscli

      # Install aws-sam-cli
      - pip3 install aws-sam-cli

      # Install project requirements
      - pip3 install -r insert_resource/requirements.txt

  pre_build:
    commands:

      # Discover and run unit tests in the 'test' directory. For more information, see <https://docs.python.org/3/library/unittest.html#test-discovery>
      - python3 -m unittest discover insert_resource/test

  build:
    commands:
      # Use AWS SAM to build and package the application by using AWS CloudFormation
      - sam build --debug
      - sam package --debug --template-file .aws-sam/build/template.yaml --s3-bucket $S3_BUCKET --output-template-file packaged.yaml


artifacts:
  type: zip
  files:
    - packaged.yaml
